### ISSUE TITLE
Roadmap next release

### ISSUE THREAD

**Issue by rvosa** [naturalis/barcode-constrained-phylogeny#79]
- [ ] refine input sequence curation as per BGE 10.1 criteria
- [ ] make OpenTol coverage denser by ssp expansion/contraction
- [ ] ensure outgroup selection avoids sequences within ingroup distances
- [ ] test exemplar selection: tallest, shallowest, average
- [ ] test rescaling subtree by exemplar cherry crown/stem ratio
